spring.application.name=journal-app
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=journal
spring.data.mongodb.auto-create-indexes=true

jwt.secret=journal-app-development-secret-key-change-this-value
